### ISSUE TITLE
error line 103

### ISSUE THREAD

**Issue by mupsje** [stevob14/cryptosignals#3]
Hi, Just wanted to test this one.
Nice code,,,

however I get a error... 

``` 
Traceback (most recent call last):
  File "/home/serveradmin/opt/jupyter/signals.py", line 103, in <module>
    prices.append( x['close'])
TypeError: string indices must be integers
```

greets Remco

**Comment by stevob14** [comment]
Hello,

It's been a while since I wrote this script. I went ahead and ran it again
to debug. Apparently coinpaprika has since updated their api plan and now
charges money to access their historical data. I attached an image of the
debug message.
The script will still work but you would have to pay to access
coinpaprika's historical data whereas it was free to access at the time
when I wrote this script. Hope this helps clear things up.

Thanks,
Stephen
